spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/erms_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Kolkata

server:
  port: 8080

#jwt:
#  secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVm
#  expiration: 2592000000

jwt:
  secret: cVBrN2tUdFd2Q2RjQk5iZ0x2T2V3S2lOeVd6WmRrY2FQbXhZcU1mYVd5V0VwR0lNQ2hQdA==
  expiration: 2592000000